In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
loan_default=pd.read_csv("Loan_default.csv")

In [4]:
loan_default.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [5]:
loan_default.tail()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [6]:
loan_default.shape

(255347, 18)

In [7]:
loan_default.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='str')

In [8]:
loan_default.dtypes

LoanID                str
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education             str
EmploymentType        str
MaritalStatus         str
HasMortgage           str
HasDependents         str
LoanPurpose           str
HasCoSigner           str
Default             int64
dtype: object

In [9]:
loan_default.info()

<class 'pandas.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  str
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  str
 11  EmploymentType  255347 non-null  str
 12  MaritalStatus   255347 non-null  str
 13  HasMortgage     255347 non-null  str
 14  HasDependents   255347 non-null  str
 15  LoanPurpose     255347 non-null  str
 16  HasCoSigner     255347 non-null  str
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), str(8)
memory usage: 35.1 MB

In [10]:
loan_default.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [11]:
loan_default.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [12]:
#convert selected numerical columns into numpy array

In [13]:
num_array=loan_default[['Age',
                         'Income',
                         'LoanAmount',
                         'CreditScore',
                         'MonthsEmployed',
                         'NumCreditLines',
                         'InterestRate',
                         'LoanTerm',
                         'DTIRatio']].to_numpy()

In [14]:
#create income category

In [15]:
loan_default["IncomeCategory"]=np.where(loan_default["Income"]>=80000,"High Income","Low Income")

In [16]:
loan_default[["Income","IncomeCategory"]].head()

   Income IncomeCategory
0   85994    High Income
1   50432     Low Income
2   84208    High Income
3   31713     Low Income
4   20437     Low Income

In [17]:
#create loan size category

In [18]:
loan_default["LoanSize"]=np.where(loan_default["LoanAmount"]>=200000,"High Loan","Low Loan")

In [19]:
loan_default[["LoanAmount","LoanSize"]].head()

   LoanAmount  LoanSize
0       50587  Low Loan
1      124440  Low Loan
2      129188  Low Loan
3       44799  Low Loan
4        9139  Low Loan

In [20]:
#save cleaned dataset

In [21]:
loan_default.to_csv("loan_default_cleaned.csv")

In [22]:
loan_default_cleaned=pd.read_csv("loan_default_cleaned.csv")

In [24]:
from sqlalchemy import create_engine
engine=create_engine=("mysql+pymysql://root:surekhasahu%40123@localhost:3306/Loan_Default")
print("starting data transfer to my sql...")

starting data transfer to my sql...

In [25]:
loan_default.to_sql("loan_default_cleaned",con=engine,if_exists="replace",index=False)

255347